### ISSUE TITLE
Sorting by votes don't work

### ISSUE THREAD

**Issue by tomwys** [CivilHub/CivilHub#1]
Sorting by votes gives following url: https://civilhub.org/warszawa-pl/ideas/?sortby=answers
in this views data seams to be sorted randomly.

**Comment by jpocentek** [comment]
Thank you for your comment. The reason is that filter names in template are not properly adjusted for database columns and sorting order is, in fact, random. Should be fixed tomorrow.

**Comment by loziniak** [comment]
It seems to not work again.
