### ISSUE TITLE
More project details

### ISSUE THREAD

**Issue by Matthias84** [CivilHub/CivilHub#10]
I think CH is a pretty interesting project, but unfortunatly it's hard to understand what it is and what it doesn't want to be. So IMHO a few more details might be useful at the readme:
- Central instance or a selfhosting platform?
- Hosting by organisations/agencies/governments/ or for the local people on the ground?
- How can govs interact / integrate it to their workflow?
- Build for activism or "just" to connect people?
- Demo out there?

**Comment by GrzegorzWarzecha** [comment]
More informations: 

https://civilhub.org/brief/
https://civilhub.org/idea-to-law/
https://civilhub.org/project-features/
https://civilhub.org/idea-to-project/
https://civilhub.org/for-city-administration/ <-- how govs can interact
https://civilhub.org/for-organizations/

CivilHub is hosted in our servers, you can register and collaborate with other people: https://civilhub.org/user/register/
