### ISSUE TITLE
Translation specs

### ISSUE THREAD

**Issue by Matthias84** [CivilHub/CivilHub#11]
Hi, IMHO it would be useful to have a small specs for translators, that explains the (non-technial) esentials about how you want a translation:
- More formal/strict or informal/friendly tone? (IMHO as Web 2.0 platform the second one?)
- Your idea of the slogans (e.g. power = force | ability)
- dict for basic terms to get an unified translation
- ...

**Comment by Matthias84** [comment]
There are still some significant bugs at the german translation. I already asked via transifex if you can grant me fullaccess, so I can alter existing (but wrong) terms directly?

**Comment by GrzegorzWarzecha** [comment]
Matthias you have now fullaccess in Transifex ;)

 Thanks for all of your work!

**Comment by Matthias84** [comment]
@GrzegorzWarzecha  Thanks for granting me access. If you push the current translation DE I will test it on your live system and will try to find the last lang issues in :-)
