### ISSUE TITLE
[Usability] Create new place

### ISSUE THREAD

**Issue by lcabrera** [CivilHub/CivilHub#13]
[Usability]
 Create new place
   Fill the fields
   I try to fill the parent field
   I have no options to select or enter a new location. Just show me the only existing options. I did not know what to do :-(

![seleccion_006](https://cloud.githubusercontent.com/assets/167067/7485768/8f2a9b7a-f392-11e4-8617-c97a4d54933d.png)

In the end, I was able to create the new location (https://civilhub.org/telde-es/), but I found it very unintuitive.

I think you should reconsider, seeking greater simplicity, the way to create new locations, preferably using only the map, which is more intuitive.

**Comment by bartekexpose** [comment]
Hola,

The current way in which you select the parent of a place is not perfect and we are aware of it but we have not yet come up with a better sollution. If you have a better way in which we can present the manual selection (i.e. the one we currently have) we would love to hear it.

If it goes for adding a place only on the map and for our system to recognize its location and finding the proper parent of the place, we plan to implement such a system in the near future (maybe even within days). However, this system may not work in 100% of cases that is why we will probably keep both.

Gracias por tu tiempo,
Bartek Bujakowski

**Comment by GrzegorzWarzecha** [comment]
Done ;)
