### ISSUE TITLE
License of user contributed content

### ISSUE THREAD

**Issue by Matthias84** [CivilHub/CivilHub#15]
The terms say that CH isn't responsible for the single material that a user contributes. On the other hand we offer this texts, photos, ... via an API to third parties that need to know how to attribute it and what they might need to fullfil?

IMHO just an public domain license (CC-0) will make no problems by attribution while saying it's user content only?

**Comment by bartekexpose** [comment]
Hi,

Everything in CivilHub, including user content, is licenced under Creative Commons 3.0, (you can find the link over here: https://creativecommons.org/licenses/by/3.0/us/), which basically says that it is in the public domain. If somoene wants to add attribution he/she needs to add a link to the page it was taken from (i.e. attribute both the author and CivlHub).

I'm not sure if this answers your question, if no, please try to reformulate your question.

Thanks for you time,
Bartek Bujakowski

**Comment by Matthias84** [comment]
Yep, it answers my questions, thanks! Maybe it's useful to mark this point on a more central place e.g. when you signup an CH account?

**Comment by bartekexpose** [comment]
As for now, we have Term of Service and Privacy Policy listed when you create a CH account, we will think about your idea of putting also licence information there. The licence subpage is fairly new and it was just recently added to the dropdown menu "about us" and in the footer, maybe that is sufficient?

**Comment by Matthias84** [comment]
I guess it's pretty ok to note it there. Maybe you want to place it more prominently, so people say 'oh cool, it's CC!'. For example stackoverflow has a note at the bottom, others have a line at the signup etc..

**Comment by bartekexpose** [comment]
We also have a CC-BY-NC-SA icon at the footer of the page, forgot to mention that :)
