### ISSUE TITLE
Nickname instead of fullname

### ISSUE THREAD

**Issue by Matthias84** [CivilHub/CivilHub#16]
While I agree that a closed project team might see my real name, I would suggest to show just a nickname at the official portal that is crawled by google etc. This keeps the users  privacy (towards the public) and avoids all the problems of 'fake accounts' (somebody claiming the name of the local mayor, politicans, ...) without checks.

**Comment by bartekexpose** [comment]
Hi,
CivilHub's policy is that everything is open to the public, we hide nothing. We prefer people when write under their real name, there is nothing to be ashamed of.

If it goes for impersonators, before someone can create a local authority site and gain the badge of a member of the city's government he/she is verified. Currently, we do this manually or automatically when someone uses a trusted email (e.g. with a city government domain ending).This is the best solution we have found out so far, however, if you have a better solution we would love to hear it.

Thanks for your time,
Bartek Bujakowski

**Comment by Matthias84** [comment]
I see your point. On the other hand the situation at least here is that it's not very common that you vote public nor that your activism get public recorded. While I see that there are pros in your approach (poss. less trolling, easy contact, ...) I can also say that this will prevent a lot of activists from joining the platform.

So I just recommend to skip the clearname-policy as it creates a lot of troubles and isn't essential to the community (e.g. trolling, spamming can be fighted via moderation, ...).

**Comment by bartekexpose** [comment]
This was not an easy decision to make and you are probably right (at least to some degree), however, at this point in time we are not thinking about reverting this policy. We might consider doing so when it will prove to be harmful to the platform.

Again, thank you for your opinion,
