### ISSUE TITLE
Image Scaling in Timeline

### ISSUE THREAD

**Issue by lcabrera** [CivilHub/CivilHub#19]
When uploading large images, the layout of the page breaks.

I think we should limit the display width in the layout or any other 'trick' to avoid the problem that you can see in the picture attached.

![wrong-layout](https://cloud.githubusercontent.com/assets/167067/7554530/f25f6a7e-f723-11e4-9e0b-3aef7fccaf6d.jpg)

Thx

**Comment by GrzegorzWarzecha** [comment]
Give us 2h. Work in progress.

**Comment by lcabrera** [comment]
**Incredible** :-)

I know this is not the appropriate channel, but I wanted to ask:

Is there a channel to communicate live? (irc, jabber, mail list, etc.)

**Comment by GrzegorzWarzecha** [comment]
Please write here, we don't have yet live communicator. 

Done.
