### ISSUE TITLE
Do projektów / ankiet określonych geograficznie przydałaby się mapka

### ISSUE THREAD

**Issue by KrzysztofMadejski** [CivilHub/CivilHub#20]
W szczególności brakuje mi mapki tutaj: https://civilhub.org/warszawa-pl/ideas/odnowa-ogrodkow-miejskich-przy-ul-mochnackiego/

Chyba, że to kwestia tego, że ktoś nie dodał loklizacji?

**Comment by GrzegorzWarzecha** [comment]
Done.
