### ISSUE TITLE
Aż się prosi o link, żeby przejść do głównej strony lokalizacji

### ISSUE THREAD

**Issue by KrzysztofMadejski** [CivilHub/CivilHub#21]
![odnowa ogrodkow miejskich przy ul mochnackiego warsaw - civilhub org 2015-05-13 17-25-00](https://cloud.githubusercontent.com/assets/849975/7614157/44eb5910-f995-11e4-8681-e8f65a9ef3ac.png)

**Comment by KarolMilewski** [comment]
done.
