### ISSUE TITLE
Drobne usprawnienie: centrowanie mapki przy tworzeniu projektu

### ISSUE THREAD

**Issue by KrzysztofMadejski** [CivilHub/CivilHub#22]
https://civilhub.org/rzeczpospolita-polska-pl/projects/create/

![civilhub - people have the power 2015-05-13 17-35-28](https://cloud.githubusercontent.com/assets/849975/7614469/38040c22-f997-11e4-9aaf-1fa699a12f3c.png)

**Comment by GrzegorzWarzecha** [comment]
In progress...

**Comment by GrzegorzWarzecha** [comment]
Ready. Close.
