### ISSUE TITLE
"You are following place" -> "Stop following place"

### ISSUE THREAD

**Issue by KrzysztofMadejski** [CivilHub/CivilHub#23]
https://civilhub.org/places/

Ponieważ zielony przycisk jest klikalny (czyli akcja nie informacja), moim zdaniem akcja powinna się znaleźć na przycisku - "Stop following <place>". No i pewnie kolorek na czerwony.

![locations 2015-05-13 17-56-45](https://cloud.githubusercontent.com/assets/849975/7614819/aa283308-f999-11e4-9c81-e0a973f1f11e.png)

**Comment by GrzegorzWarzecha** [comment]
Done.
