### ISSUE TITLE
Komentowanie tasków

### ISSUE THREAD

**Issue by KrzysztofMadejski** [CivilHub/CivilHub#24]
Wyskoczył mi taki task https://civilhub.org/warszawa-pl/projects/drobne-ulatwienie-przy-miejskim-rowerze/
, w timeline, zaciekawił, chciałem go skomentować jakoś, ale nie widzę takiej opcji..

**Comment by GrzegorzWarzecha** [comment]
W timeline jeszcze nie mamy możliwości komentowania. Komentować można bezpośrednio w widoku tasku w projekcie. 

Pracujemy nad tym, aby była  możliwość komentowania różnych treści bezpośrednio z timeline.

**Comment by GrzegorzWarzecha** [comment]
Możliwość komentowania w timeline została dodana ;)
