### ISSUE TITLE
Wyszukiwarka - focus

### ISSUE THREAD

**Issue by KrzysztofMadejski** [CivilHub/CivilHub#25]
W górnym pasku po kliknięciu ikonki wyszukiwania focus mógłby się ustawiać na input, tak żeby od razu można było wpisywać frazę z klawiatury.

![your feed 2015-05-13 19-04-18](https://cloud.githubusercontent.com/assets/849975/7616257/56fde15a-f9a3-11e4-98d5-b1702e41be84.png)

**Comment by GrzegorzWarzecha** [comment]
Bardzo dobry pomysł, w przyszłym tygodniu będzie :)

**Comment by KarolMilewski** [comment]
Done.
