### ISSUE TITLE
Na feedzie nie można doscrollować się do zmiany języka na dole

### ISSUE THREAD

**Issue by KrzysztofMadejski** [CivilHub/CivilHub#26]
Co ze stopką w feed?

**Comment by GrzegorzWarzecha** [comment]
Bardzo podobna sytuacja jest na Twitterze czy FB, nie da się doscrollować do dołu aby zobaczyć stopkę. ;) W naszej opinii może to tak zostać, chyba że zgłosi się więcej osób którym to przeszkadza, wtedy możemy zmianę języka w "feedzie" przenieść na lewo lub na prawo.

**Comment by GrzegorzWarzecha** [comment]
Obecnie doszliśmy do wniosku, że nie warto tego zmieniać.
