### ISSUE TITLE
Punkty - leaderboard? historia? informacja o tym 

### ISSUE THREAD

**Issue by KrzysztofMadejski** [CivilHub/CivilHub#27]
W profilu wyświetlana jest informacja "Punkty: 4". Fajnie byłoby się dowiedzieć:
- za co je dostałem
- za co je mogę dostać [punktacja]
- leaderboard [ogólnie, wśród znajomych]

**Comment by Matthias84** [comment]
@KrzysztofMadejski can you plz. translate your issues to EN, so everybody can participate and join in the discussion? :-)

**Comment by GrzegorzWarzecha** [comment]
In progress...

**Comment by GrzegorzWarzecha** [comment]
Strona została przygotowana. Zamykam ;)
