### ISSUE TITLE
translating HTML pages

### ISSUE THREAD

**Issue by Matthias84** [CivilHub/CivilHub#28]
Hi there, thanks for adding the HTML pages, so we can start with an I18n here. Unfortunatly, it seems that currently this includes also a lot of codesnippets that don't contain content that we need to translate.

So can we clean the transifex in that way, that only things appear that we need to translate within the HTML files, please?

**Comment by GrzegorzWarzecha** [comment]
Give us few days

**Comment by Matthias84** [comment]
Just give me a ping if you finished the files.

**Comment by bartekexpose** [comment]
Hi,

I have looked through the translations and found out the source of the problem in one file. The "brief" page was uploaded incorrectly which resulted in a lot of code snippets. I have fixed that and it should now be more readable.

If it goes for the rest of the pages there is, to the best of my knowledge, little that can be done with the code snippets as transifex cuts the text by itself and I have not yet found a solution as to where I could manually do that without breaking the code.

However, there is a simple work-around solution build-in transifex, which is the <b>"Enable HTML editor"</b> option that can be found in the top right corner in the settings (cog icon). I believe that this option and the above brief page fix should be sufficient.

Please tell me if if the way the translations look right now is acceptable. If not I will try to find another sollution.

Thanks,

**Comment by Matthias84** [comment]
Hi thanks for the hint, this seems to work. I will start with a translation soon, but as this is a lot of stuff I need a bigger chunk of time :)
