### ISSUE TITLE
Missing space in "please add first poll"

### ISSUE THREAD

**Issue by d33tah** [CivilHub/CivilHub#3]
See here:

https://civilhub.org/rzeczpospolita-polska-pl/polls/

**Comment by GrzegorzWarzecha** [comment]
Could you explain?

**Comment by d33tah** [comment]
https://i.imgur.com/6qz0QkR.png

**Comment by d33tah** [comment]
There's a space missing between "Proszę" and "dodaj".

**Comment by GrzegorzWarzecha** [comment]
Thanks!
