### ISSUE TITLE
Infinite points from voting

### ISSUE THREAD

**Issue by Teiron** [CivilHub/CivilHub#30]
Every time I cast a vote in ideas section I get a point, no matter how many times I voted in a particular poll, I can just keep voting and renouncing my vote to get infinite amount of points for my account.

PL: Za każdym razem gdy głosuje w pomyśle dostaje punkt, niezależnie od tego czy głosuje pierwszy raz czy ciągle odwołuje swój głos i ponownie głosuje. Moim zdaniem punkty powinny być za uczestnictwo nie zaś za  ciągłe zmienianie zdania.

**Comment by jpocentek** [comment]
Fixed.

**Comment by Teiron** [comment]
Thanks
