### ISSUE TITLE
Updating translations?

### ISSUE THREAD

**Issue by Matthias84** [CivilHub/CivilHub#32]
Hi, could you please update the translations on civilhub.org? Currently there are still pretty bad mechanical translation artefacts that are already fixed at transifex for some time :/

**Comment by GrzegorzWarzecha** [comment]
We update translations everyday. Now, I pull all translations from transifex.

**Comment by GrzegorzWarzecha** [comment]
It's ok?

**Comment by Matthias84** [comment]
Looks good, thank you. I will start on improving DE next week if I have more time. Of course then I will continue to finish with the HTML pages etc... :)

**Comment by Matthias84** [comment]
@GrzegorzWarzecha 
It seems that some of my translations had been replaced as there are still some hard bugs (map -> Mappe) that I fixed already. I guess I need to review that again

**Comment by bartekexpose** [comment]
Hi,

We have discovered the problem of correcting translations. Only coordinators have the ability to do that. We can grant you coordinatior rights if you tell us your username on transifex (as there are more people with the name of Matthias there).

You can post it here or send me an e-mail with your name to bartek@expose.pl

**Comment by Matthias84** [comment]
I guess it was my fault, as my memories were just wrong. At the beginning as you say I didn't had the privileges to alter translated strings, so I just commented them. But now I (user:thinkplate) has the rights and yesterday I fixed this strings :-)

**Comment by Matthias84** [comment]
@bartekexpose At weekend I fixed some very wrong translations at transifex, but it seems they rolled back? Can you please check if there is an problem, as it seems the webclient works fine :-/

**Comment by GrzegorzWarzecha** [comment]
Give us examples of wrong translations.

Wysłano z mojego smartfona w PLAY

<div>-------- Oryginalna wiadomość --------</div><div>Od: Matthias84 notifications@github.com </div><div>Data:29.06.2015  20:07  (GMT+01:00) </div><div>Do: CivilHub/CivilHub CivilHub@noreply.github.com </div><div>DW: Grzegorz Warzecha grzegorz@civilhub.org </div><div>Temat: Re: [CivilHub] Updating translations? (#32) </div><div>
</div>@bartekexpose At weekend I fixed some very wrong translations at transifex, but it seems they rolled back? Can you please check if there is an problem, as it seems the webclient works fine :-/

**Comment by Matthias84** [comment]
@GrzegorzWarzecha see "map" which is currently wrong "mappe" but I already fixed it a couple of times to "Karte" -.-

**Comment by GrzegorzWarzecha** [comment]
We have problem with transifex… We must change transifex to other platform. 

-- 
Pozdrawiam, 
Regards, 

Grzegorz Warzecha
+48 782 421 117

Founder CivilHub
Jasna 10/200
00-013 Warsaw
Poland
https://civilhub.org

P.S
I'm living in Poland, if you want speak, please call me. Usually UTC +2, CEST time ;) 

W dniu 3 lipca 2015 @ 23:45:02, Matthias84 (notifications@github.com) napisał(a):

@GrzegorzWarzecha see "map" which is currently wrong "mappe" but I already fixed it a couple of times to "Karte" -.-

**Comment by Matthias84** [comment]
@GrzegorzWarzecha I updated DE yesterday, could you please push the changes?
