### ISSUE TITLE
Connecting accounts

### ISSUE THREAD

**Issue by milovanderlinden** [CivilHub/CivilHub#39]
I would like to add all external accounts (Google, LinkedIn, Facebook) to my profile so I can invite friends from the various platforms. Would this be possible (in the future?)

**Comment by jpocentek** [comment]
You can try to log in with different account (for example using button "login with google"). It should connect your account as long as you're using the same email address. There are separate options with every account, but all should be compatible. It works with my Facebook and G+ account. Please let me know if you'll experience any problems with this.
