### ISSUE TITLE
Instruction for pip install is not complete

### ISSUE THREAD

**Issue by milovanderlinden** [CivilHub/CivilHub#41]
Readme.md reads:

``` bash
pip install -r requirements
```

but should read:

``` bash
pip install -r requirements.txt
```

**Comment by milovanderlinden** [comment]
Also, run the pip install command with sudo rights or it will fail (unless you are in a virtualenv of course)

**Comment by jpocentek** [comment]
I'm sorry, I've updated yout comment unintentionally.

Thanks for your comment. Problem with .txt extension is fixed now. As for virtualenv and project installation, I think it's all explained pretty well in Python and PIP docs. Also, instructions may vary depending on what OS you use. Personally I think that using virtualenv is always the best option, but that also may vary.
