### ISSUE TITLE
Kliknięcie na "Miejsca" powinno moim zdaniem pokazywać obserwowane lokalizacje

### ISSUE THREAD

**Issue by KrzysztofMadejski** [CivilHub/CivilHub#5]
![civilhub1](https://cloud.githubusercontent.com/assets/849975/7230052/9e2224d8-e76a-11e4-83c9-c0d4bd3e504a.PNG)

**Comment by KarolMilewski** [comment]
Zostało to już poprawione, jedynie zmiany nie zostały dodane do civilhub.org. Będzie to dodane w  najbliższym update.

**Comment by GrzegorzWarzecha** [comment]
Done. ;)
