### ISSUE TITLE
Switch from Transiflex

### ISSUE THREAD

**Issue by Matthias84** [CivilHub/CivilHub#9]
Hi, if I finished the german translation I would recommend that you consider to switch from Transiflex to a more open and non commercial alternative to do crowd i18n:
- [launchpad](https://translations.launchpad.net/)
- [translatewiki](https://translatewiki.net)
- ...

While saving the communities work (avoid training an commercial AI) this might also help to get new folks to translate other languages, too :-)

**Comment by GrzegorzWarzecha** [comment]
Hi, thank you for german translation. 

Transifex have one greate feature. Automate merge & sync translations, using comand line tool. 

Django, and muny other repositories use transifex, because is faster for Python project than launchpad or translatewiki. ;)

**Comment by Matthias84** [comment]
Thanks for your feedback. I see that you seem to considered alternatives, but Transifex matchs better to your workflow :-)

**Comment by GrzegorzWarzecha** [comment]
Thanks for your translation. :)
4 maj 2015 18:40 "Matthias84" notifications@github.com napisał(a):

**Comment by GrzegorzWarzecha** [comment]
Zostałeś zaproszony na następujące wydarzenie.

Tytuł: Spotkanie
Kiedy: śr. 2015-07-22 12:30 - 13:00 Warszawa
Kalendarz: Grzegorz Warzecha
Kto:
     \* Grzegorz Warzecha- organizator
     \*  
reply@reply.github.com

Szczegóły wydarzenia:  
https://www.google.com/calendar/event?action=VIEW&eid=NjFoajhkcGw2NHFtNmJiMjZvcDZjYjlrY3BoNjJiOW82Z3MzZ2JiMjZvbzNpYzFqNjBvbWNkMzZjOCByZXBseSswMDRkNDViYzJkMzA0NDhmNzhkZGM2MWZlNjQ1NTk4MGM5MGUxYzc5MTk5NDMyNDQ5MmNmMDAwMDAwMDExMTVmNjJlYjkyYTE2OWNlMDQ1NDFhMjdAcmVwbHkuZ2l0aHViLmNvbQ&tok=MTgjZ3J6ZXdhcnpAZ21haWwuY29tMmU3NjFmOTdkMTI0N2I2NzRkMTBlYWI5MjhjMGExOWJkMjllYTQ0Ng&ctz=Europe/Warsaw&hl=pl

Zaproszenie z Kalendarza Google: https://www.google.com/calendar/

Wiadomość grzecznościowa została wysyłana do Ciebie na adres  
reply@reply.github.com,  
ponieważ uczestniczysz w tym wydarzeniu.

Aby zrezygnować z otrzymywania w przyszłości powiadomień dotyczących tego  
wydarzenia, odrzuć je. Zamiast tego możesz też założyć sobie konto Google  
na https://www.google.com/calendar/ i samodzielnie decydować o ustawieniach  
powiadomień dla całego swojego kalendarza.

Przekazanie tego zaproszenia może spowodować, że każdy z jego odbiorców  
będzie mógł zmodyfikować Twoją odpowiedź. Więcej informacji na stronie:  
https://support.google.com/calendar/answer/37135#forwarding
